name: Build All Platforms

on:
  push:
    tags:
      - 'v*'  # 当推送 v1.0.0 这样的 tag 时触发
  workflow_dispatch:  # 也支持手动触发

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          # Windows x64
          - os: windows-latest
            platform: windows
            arch: amd64
            ext: .exe
            
          # Linux x64
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            ext: ''
            
          # macOS Intel
          - os: macos-13
            platform: macos
            arch: amd64
            ext: ''
            
          # macOS Apple Silicon
          - os: macos-14
            platform: macos
            arch: arm64
            ext: ''

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 构建可执行文件 (Windows)
        if: matrix.platform == 'windows'
        run: |
          python -m PyInstaller --onefile --name CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }} --clean --console --hidden-import requests --hidden-import urllib3 --hidden-import certifi --hidden-import charset_normalizer --hidden-import idna --exclude-module tkinter --exclude-module matplotlib --exclude-module numpy --exclude-module pandas --exclude-module PIL --exclude-module cv2 --exclude-module scipy --strip --optimize 2 cloudflare_speedtest.py

      - name: 构建可执行文件 (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          # 使用验证成功的命令，解决 macOS 符号链接问题
          python -m PyInstaller --onefile --name CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }} --clean --console --hidden-import requests --hidden-import urllib3 --hidden-import certifi --hidden-import charset_normalizer --hidden-import idna --exclude-module tkinter --exclude-module matplotlib --exclude-module numpy --exclude-module pandas --exclude-module PIL --exclude-module cv2 --exclude-module scipy --strip --optimize 2 cloudflare_speedtest.py

      - name: 重命名文件（Windows）
        if: matrix.platform == 'windows'
        run: |
          move dist\CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }}.exe dist\CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: 赋予执行权限（Linux/macOS）
        if: matrix.platform != 'windows'
        run: chmod +x dist/CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/CloudflareSpeedTest-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}
          retention-days: 30

  # 创建 Release（当推送 tag 时）
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: 显示下载的文件
        run: ls -R ./artifacts

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/CloudflareSpeedTest-windows-amd64/CloudflareSpeedTest-windows-amd64.exe
            artifacts/CloudflareSpeedTest-linux-amd64/CloudflareSpeedTest-linux-amd64
            artifacts/CloudflareSpeedTest-macos-amd64/CloudflareSpeedTest-macos-amd64
            artifacts/CloudflareSpeedTest-macos-arm64/CloudflareSpeedTest-macos-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ##  Cloudflare SpeedTest 跨平台版本
            
            ### 📦 包含文件
            - **Windows (x64)**: CloudflareSpeedTest-windows-amd64.exe
            - **Linux (x64)**: CloudflareSpeedTest-linux-amd64
            - **macOS (Intel)**: CloudflareSpeedTest-macos-amd64
            - **macOS (Apple Silicon)**: CloudflareSpeedTest-macos-arm64
            
            ###  功能特性
            - 🎯 内置 97 个全球数据中心机场码
            - 🌍 支持城市名称智能识别（如"香港"、"东京"）
            - ⚙️ 预设配置：快速/标准/高质量测试
            - 🔧 完全自定义参数
            - 📊 自动生成测速报告
            
            ###  使用方法
            1. 下载对应平台的可执行文件
            2. 双击运行（Windows）或赋予执行权限（Linux/macOS）
            3. 按提示选择机场码和测试配置
            4. 等待测速完成，查看 result.csv 结果文件

